# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  install_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn install --immutable

  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn install --immutable

  build:
    needs: [install]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn run build

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: build
          key: build-${{ github.sha }}

  lint:
    needs: [install]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn run lint

  test:
    needs: [install]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4

  cypress:
    needs: [install, build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Restore build
        uses: actions/cache@v3
        with:
          path: build
          key: build-${{ github.sha }}

      - name: Cypress run
        timeout-minutes: 2
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          install: false
          start: yarn start:ci
          wait-on: 'http://localhost:3000'
          browser: chrome

  deploy:
    needs: [install, build, test, cypress]
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Restore build
        uses: actions/cache@v3
        with:
          path: build
          key: build-${{ github.sha }}

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
